### ISSUE TITLE
Not working with SvelteKit

### ISSUE THREAD

**Issue by benwoodward** [wareset/svelte-use-mousetrap#1]
Thanks for this package. Just FYI, it's not working with SvelteKit due to `mousetrap` not having an ESM export unfortunately. 

```
> Cannot use import statement outside a module
/Users/ben/dev/my-project/node_modules/svelte-use-mousetrap/index.js:1
import Mousetrap from 'mousetrap';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async prerender (file:///Users/ben/dev/my-project/node_modules/@sveltejs/kit/dist/chunks/index5.js:79:14)
    at async Object.prerender (file:///Users/ben/dev/my-project/node_modules/@sveltejs/kit/dist/chunks/index5.js:296:5)
```

**Comment by wareset** [comment]
Hello. Thanks) Uploaded to the npm. Now there are two files - js (like cjs) and mjs. This should work
